name: CI - Micapipe Test

on:
  push:
    branches: []
  pull_request:

jobs:
  run-micapipe:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Micapipe Docker image
        run: docker build -t micapipe:test -f ./micapipe/old/Dockerfile .

      - name: Build Singularity (.sif)
        run: singularity build micapipe.sif docker-daemon://micapipe:test

      - name: Point test script at new .sif
        run: |
          sed -i "s|^container_img=.*|container_img=$(pwd)/micapipe.sif|" tests/sample_test.sh

      - name: Run Micapipe Test
        run: |
          chmod +x ./tests/sample_test.sh
          ./tests/sample_test.sh
